### PR TITLE
Fix: possible crash on SearchActivity

### PR DESCRIPTION
**Pull request by cooltey**
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/3718384554u/overview

Looks like there has another type of `INTENT`, which will cause a crash if the `source` is `null`.

### CODE REVIEW

**Comment by dbrant** [comment]
@cooltey  This does not seem to be happening in the latest Beta (50346).  Let's wait to see if we encounter it again before merging this.

**Comment by sharvaniharan** [comment]
Is this on hold? should we have a label on this @cooltey

**Comment by cooltey** [comment]
> 
> 
> Is this on hold? should we have a label on this @cooltey

Yes, we can hold this ticket until the next release.

**Comment by cooltey** [comment]
@dbrant @sharvaniharan 
62 users having the same crash on the latest production in 30 days.
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/2592442938u/overview

**Pull request merged**
