### PR TITLE
 Patroller tasks: build the screen for managing the warn templates

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T343841

### CODE REVIEW

**Review by dbrant — COMMENTED** [review]
@cooltey  Before we go much further, can we break these strings out into a separate PR, so they can get merged into master and synced to TWN?

In fact, can we also do this for the remaining strings related to Patroller Tasks, listed in the spreadsheet linked in https://phabricator.wikimedia.org/T343287

**Comment by cooltey** [comment]
> @cooltey Before we go much further, can we break these strings out into a separate PR, so they can get merged into master and synced to TWN?
> 
> In fact, can we also do this for the remaining strings related to Patroller Tasks, listed in the spreadsheet linked in https://phabricator.wikimedia.org/T343287

Sure and done! #4151

**Comment by cooltey** [comment]
@dbrant @sharvaniharan The PR is ready for review.

**Comment by cooltey** [comment]
Currently working on integrating the new wikitext keyboard, please do not merge this.

**Comment by cooltey** [comment]
@dbrant @sharvaniharan 

This is ready for review again. The `textInputDialog` (in editing mode) will not show the wikitext keyboard since the layout will be contained in the dialog.

**Review by sharvaniharan — CHANGES_REQUESTED** [review]
I see the delete message has no quotes around the message title: <Name of message is 'Close' in this case>. the design on Figma and screenshot 9 have quotes around the title.
Screenshot 2023-10-13 at 11 36 03 AM

**Comment by sharvaniharan** [comment]
I feel we should have an empty check for the subject field, since currently I am able to just leave it effectively empty by just typing spaces.
Screenshot 2023-10-13 at 11 48 17 AM

**Comment by sharvaniharan** [comment]
When we edit an existing template by long-press, the title changes do not reflect on the list:
https://youtube.com/shorts/aikNpf_blT0?feature=share

**Comment by sharvaniharan** [comment]
When we try to save a template, if we hit cancel, the save button becomes disabled again until we type something to the original message/subject:
https://youtube.com/shorts/j8bOTe9U8zA?feature=share

**Comment by sharvaniharan** [comment]
@cooltey My review is done and once these are fixed will be ready to merge.

**Comment by cooltey** [comment]
Thanks for the code review, @sharvaniharan. The comments you've mentioned should be addressed.

**Comment by sharvaniharan** [comment]
@cooltey Thank you for updating. 
- Looks like the string is still not updated here - if you were waiting for merge, it is merged now, and let's use the new string here
- List update after title change is still not working for me 
- The save disabling.. could we keep showing the subject error hint message while the subject is still empty? making it go away and again make it pop when they try to save could be frustrating. Lmk what you think.: https://youtube.com/shorts/M7fh-MGgjPw?feature=share

**Comment by cooltey** [comment]
> @cooltey Thank you for updating.
> 
>     * Looks like the string is still not updated here - if you were waiting for merge, it is merged now, and let's use the new string here
> 
>     * List update after title change is still not working for me
> 
>     * The save disabling.. could we keep showing the subject error hint message while the subject is still empty? making it go away and again make it pop when they try to save could be frustrating. Lmk what you think.: https://youtube.com/shorts/M7fh-MGgjPw?feature=share

Hi @sharvaniharan, I updated the text for the dialog, and please make sure to reinstall the app (or clean the app data) to be able to test the swap/update/delete function. 

About the error hint message, maybe we can create a ticket about improving the error message handling in the input field.

**Comment by sharvaniharan** [comment]
Hi @cooltey 
Everything checks out. However, now i am having same issue with updating content. As long as there is a title, it saves the template without warnings, even if subject and content are clear. Different behavior than when we create a new template. Is this something we can fix, or need to ask Olga?

**Comment by cooltey** [comment]
> Hi @cooltey Everything checks out. However, now i am having same issue with updating content. As long as there is a title, it saves the template without warnings, even if subject and content are clear. Different behavior than when we create a new template. Is this something we can fix, or need to ask Olga?

Good catch! Done! Please also help to test the "add template" flow since they are sharing the same dialog, thanks!

**Pull request merged**
