### PR TITLE
Replace the theme color button with plain circular buttons

### PR DESCRIPTION
**Pull request by cooltey**
We have to resize (re-style) the theme color buttons in order to add font-family buttons to the theme dialog.
https://phabricator.wikimedia.org/T264445

### CODE REVIEW

**Comment by sharvaniharan** [comment]
The circle looks very good. Couple things:
- The dark and Black circle colors might need to be more different. dark mode color needs to be slightly lighter i guess
- May be a single capital letter inside the circle? 'L' 'S' 'D' and 'B'?

**Comment by cooltey** [comment]
> 
> 
> The circle looks very good. Couple things:
> 
>     * The dark and Black circle colors might need to be more different. dark mode color needs to be slightly lighter i guess
> 
>     * May be a single capital letter inside the circle? 'L' 'S' 'D' and 'B'?

Thanks! I'll share the comment with Robin, it's a great suggestion.

**Comment by cooltey** [comment]
@dbrant @sharvaniharan I removed the Experimental tag since Robin has confirmed the design and it is ready for review now.

**Comment by dbrant** [comment]
Yes! And a bunch of code removed, too.

**Pull request merged**
