### PR TITLE
Use Context.getSystemService() extension.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Comment by dbrant** [comment]
In what way is this better?

**Comment by Isira-Seneviratne** [comment]
It avoids the need for a separate cast to the service class.

**Comment by dbrant** [comment]
> It avoids the need for a separate cast to the service class.

No, it doesn't. The cast simply happens in a different place.

**Comment by Isira-Seneviratne** [comment]
Yeah, I meant the casting doesn't have to be done in the app code itself.

**Pull request closed without merging**
