### PR TITLE
Swipe actions for notifications list view

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T288065

### CODE REVIEW

**Comment by cooltey** [comment]
@dbrant @sharvaniharan Conflicts resolved and ready for review now.

**Comment by sharvaniharan** [comment]
Lgtm... the only question I had was that the more menu option strings look different .. Like "@username" instead of "View @username's user profile page", etc. Please let me know and I am ready to merge.

**Comment by cooltey** [comment]
> 
> 
> Lgtm... the only question I had was that the more menu option strings look different .. Like "@username" instead of "View @username's user profile page", etc. Please let me know and I am ready to merge.

Ah! That's something I forgot to mention to Robin. I'll let him know the reason and thanks for catching that.

**Comment by sharvaniharan** [comment]
ok will merge this then... :) you can make a tweak if needed..

**Pull request merged**
