### PR TITLE
Tweak: keep "deep link" users in the app when pressing the back button

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T224789#5306112

### CODE REVIEW

**Comment by sharvaniharan** [comment]
just checking app.haveMainActivity() might not be enough here... if we have stuff on the stack it will not work as expected:

https://youtu.be/yXTG0AUqpR4

**Comment by cooltey** [comment]
@sharvaniharan This PR fixes the issue when users open a deep link from a web browser, the "back" button show go back to the explore feed. It does not relate to the issue you've mentioned.

**Comment by sharvaniharan** [comment]
but the ticket mentions that the system back should take them back to chrome and stay in the app. That is what is not happening as seen in the video..

**Comment by sharvaniharan** [comment]
Sorry the link was wrong . Here is the correct one
https://youtu.be/y78VDTH043g

Sorry for the confusion.

**Comment by sharvaniharan** [comment]
@cooltey as discussed offline, I will post the video on the ticket since the system back button only works on a fresh launch as expected. I agree that it will be too much code to maintain, in order to detect a deep-link launch and behave differently. Will post the video on the ticket too, so Robin is aware of this decision.

**Pull request merged**
