### PR TITLE
Update gradle plugins versions

### PR DESCRIPTION
**Pull request by cooltey**
Update com.android.tools.build:gradle to 4.2.0
Update gradle to 6.7.1

### CODE REVIEW

**Comment by dbrant** [comment]
Can we hold on merging this for a bit; Upgrading to 4.2.0 causes the build to start failing on my Windows workstation, and I have no idea why.

**Comment by dbrant** [comment]
Ha, looks like the build fails in CI, too

**Comment by cooltey** [comment]
> 
> 
> Ha, looks like the build fails in CI, too

Not sure if it relates to the Kotlin plugin version, since it shows a recommended version `1.5.0-release-764` that doesn't make sense to me. Will wait and see if a newer update pops up later.

**Comment by sharvaniharan** [comment]
Build id failing for me to ..

**Comment by dbrant** [comment]
I traced the failure down to the way it processes our resources, and it looks like it no longer likes the `be+tarask` language.  Renaming that resource collection to `be-x-old` seems to fix it.

Personally I would just delete this language altogether, since on a real Android device there's no way to actually select this language as your system UI language.

Let's wait to merge this until my patch upstream to TWN is merged: https://gerrit.wikimedia.org/r/c/translatewiki/+/686735

**Comment by cooltey** [comment]
> I traced the failure down to the way it processes our resources, and it looks like it no longer likes the `be+tarask` language.  Renaming that resource collection to `be-x-old` seems to fix it.
> 
> Personally I would just delete this language altogether, since on a real Android device there's no way to actually select this language as your system UI language.
> 
> Let's wait to merge this until my patch upstream to TWN is merged: https://gerrit.wikimedia.org/r/c/translatewiki/+/686735

Sounds good! Thanks for checking and fixing.

**Pull request merged**
