### PR TITLE
WebView right-click behavior for physical mouse devices.

### PR DESCRIPTION
**Pull request by dbrant**

### CODE REVIEW

**Comment by dbrant** [comment]
@cooltey  Would you mind testing this on the Chromebook, and see how the right-click behavior works?

**Comment by cooltey** [comment]
@dbrant 
The behavior of right-clicking on the non-URL text is really great (to see the default floating toolbar), but right-click on hyperlinks requires a "long" right-click to trigger the dialog.

**Comment by dbrant** [comment]
> @dbrant
> The behavior of right-clicking on the non-URL text is really great (to see the default floating toolbar), but right-click on hyperlinks requires a "long" right-click to trigger the dialog.

Can this be an acceptable tradeoff, while making this functionality as simple as possible?

**Comment by cooltey** [comment]
> 
> 
> > @dbrant
> > The behavior of right-clicking on the non-URL text is really great (to see the default floating toolbar), but right-click on hyperlinks requires a "long" right-click to trigger the dialog.
> 
> Can this be an acceptable tradeoff, while making this functionality as simple as possible?

Yes, of course. It is definitely a simpler solution for the Webview right-click event. Is it okay to be merged now?

**Comment by dbrant** [comment]
OK to merge!

**Pull request merged**
