### PR TITLE
Design tweak for onboarding screen

### PR DESCRIPTION
**Pull request by sharvaniharan**
https://phabricator.wikimedia.org/T331272#8739476

- Apply themed color to border

### CODE REVIEW

**Review by dbrant — CHANGES_REQUESTED** [review]
This makes the third onboarding illustration look completely different from the first two:

Screenshot_20230330_100700 Screenshot_20230330_100647

Is this really what we want? The "W" and the robot icons are also barely visible on a dark background.

**Comment by sharvaniharan** [comment]
Updated @dbrant .. how about now?

**Comment by dbrant** [comment]
> Updated @dbrant .. how about now?

I'm not seeing anything changed.

**Comment by sharvaniharan** [comment]
Sorry forgot to push! ready now!

**Pull request merged**
