### PR TITLE
Improve save to reading list UX

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T256821

TODO: update revision number once the schema is updated
https://phabricator.wikimedia.org/T256821#6352975

### CODE REVIEW

**Comment by sharvaniharan** [comment]
@cooltey Looks good, but i had a couple questions, which might need Robin's input, so directly updated on ticcket.

**Comment by sharvaniharan** [comment]
@cooltey Found an issue: Article save button is not working

**Comment by sharvaniharan** [comment]
https://youtu.be/f4LeCkyy0OMv

**Comment by cooltey** [comment]
> 
> 
> @cooltey Found an issue: Article save button is not working

Thanks, nice catch! The code was accidentally removed on my previous commit.

**Pull request merged**
