### PR TITLE
Create Onboarding for Patroller Tasks

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T343242

### CODE REVIEW

**Comment by sharvaniharan** [comment]
@cooltey if this is `wip` only for the data wiring, you can leave and `Todo:` and open for review... i will fill it in during data wiring.

**Comment by cooltey** [comment]
> @cooltey if this is `wip` only for the data wiring, you can leave a `Todo:` and open for review... i will fill it in during data wiring.

We will still need to work on adding tooltips for the diff screen once we merge the diff screen PR to the feature branch.

**Comment by sharvaniharan** [comment]
@cooltey I was shown the data permission [3rd] slide, even though i had opted in to sharing data. I thought we agreed we will not show that slide to opted in users.
https://youtube.com/shorts/WmtNZ7vN6-M?feature=share

**Comment by sharvaniharan** [comment]
Another minor issue. I see `%` symbol next to Damage and intent values, but do not see it in the actual screens.

**Comment by sharvaniharan** [comment]
Fixed on #4240 So merging this.

**Pull request merged**
