### PR TITLE
Request media endpoints when saving articles offline

### PR DESCRIPTION
**Pull request by cooltey**
Use the cached in-article images for Gallery to reduce unnecessary downloads.

https://phabricator.wikimedia.org/T226290

### CODE REVIEW

**Comment by cooltey** [comment]
Note: "Could not draw the image" message will show if the image download process was not completed. Need to update the `savePageFor()` method in `SavedPageSyncService()`

**Comment by dbrant** [comment]
[pending clarifying comment on Phab]

**Comment by cooltey** [comment]
@dbrant Changes are done.

**Comment by cooltey** [comment]
Pending discussion: https://phabricator.wikimedia.org/T226290#5398079

**Comment by cooltey** [comment]
Close and will create a new PR for the update status:
https://phabricator.wikimedia.org/T226290#5403040

**Pull request closed without merging**
