### PR TITLE
Fix display of non-public revisions in Diff view.

### PR DESCRIPTION
**Pull request by dbrant**
https://phabricator.wikimedia.org/T343044

### CODE REVIEW

**Review by cooltey — CHANGES_REQUESTED** [review]
The "Thank" and "Undo" buttons will show up for a few seconds while loading the revision, even if it is a private revision. 

https://youtube.com/shorts/7dnRnXPC8V8

**Comment by dbrant** [comment]
> The "Thank" and "Undo" buttons will show up for a few seconds while loading the revision, even if it is a private revision.

And.. fixed!

**Comment by cooltey** [comment]
> > The "Thank" and "Undo" buttons will show up for a few seconds while loading the revision, even if it is a private revision.
> 
> And.. fixed!

That's better!

Just noticed another issue if I change the device's orientation, the buttons will show up again.

**Comment by dbrant** [comment]
> Just noticed another issue if I change the device's orientation, the buttons will show up again.

Done!!!111

**Pull request merged**
