### PR TITLE
Set up article Uri correctly for Chinese variants

### PR DESCRIPTION
**Pull request by cooltey**
When sharing page links on Chinese articles, we should give the user a correct link with proper language variant.

For example: 
https://zh.wikipedia.org/zh-hant/2019冠状病毒病西班牙疫情 for Traditional Chinese
instead of 
https://zh.wikipedia.org/wiki/2019冠状病毒病西班牙疫情 (default page that has mixed variants)

### CODE REVIEW

**Comment by dbrant** [comment]
Looks good. How about a couple of quick unit tests in `PageTitleTests` to test these variants?

**Comment by cooltey** [comment]
> Looks good. How about a couple of quick unit tests in `PageTitleTests` to test these variants?

Makes sense. Will do it!

**Comment by cooltey** [comment]
> Looks good. How about a couple of quick unit tests in `PageTitleTests` to test these variants?

Done!

**Comment by dbrant** [comment]
very nice

**Pull request merged**
