### PR TITLE
Use totally random query for image tags.

### PR DESCRIPTION
**Pull request by dbrant**

### CODE REVIEW

**Comment by sharvaniharan** [comment]
This is so much better than the suggested images! It would have been great if this was shipped! 🌟

**Comment by dbrant** [comment]
There's every possibility we'll ship this as a follow-up afterwards.  The one minor problem with this is that it doesn't detect if the random image _already_ has tag(s).  That will require a few more rather complex queries.

**Comment by sharvaniharan** [comment]
oh nice! makes sense..

**Comment by cooltey** [comment]
This is definitely a better implementation than the current one. Nice job 👍

**Pull request merged**
