### PR TITLE
Update setup-java action to v2 for workflows

### PR DESCRIPTION
**Pull request by nuhkoca**
Updating the [setup-java](https://github.com/actions/setup-java) action to v2. 

- V2 supports custom distributions and provides support for `Zulu OpenJDK`, `Eclipse` `Temurin` and `Adopt OpenJDK`. V1 supports only `Zulu OpenJDK`.
- V1 supported legacy Java syntax such as 1.8 (same as 8) and 1.8.0.212 (same as 8.0.212). V2 dropped support for legacy syntax.

### CODE REVIEW

**Comment by nuhkoca** [comment]
Would be good if I could get some Hactoberfest points for this PR 😬

**Comment by dbrant** [comment]
The documentation says:

> Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from `adopt` to `temurin` to keep receiving software and security updates.

Can we use `temurin` instead?

**Comment by nuhkoca** [comment]
@dbrant good point! I was just going to mention `Temurin`, as well. I will change the distributor then. Thanks!

**Comment by nuhkoca** [comment]
@dbrant ready for review!

**Pull request merged**
