### PR TITLE
Fix: don't create a default list every time when upgrading the database

### PR DESCRIPTION
**Pull request by cooltey**
The `currentLists` is empty, so it will let the `createDefaultList()` create a default list every time when upgrading the database.

### CODE REVIEW

**Comment by dbrant** [comment]
Sorry, what issue is this fixing?  Where is the default list being recreated?

**Comment by cooltey** [comment]
> 
> 
> Sorry, what issue is this fixing? Where is the default list being recreated?

This relates to this PR: #448 since the db version will be updated to `19`.

**Comment by dbrant** [comment]
...But that code won't run, will it? It should only run when the DB is upgraded to 18.

**Comment by cooltey** [comment]
> 
> 
> ...But that code won't run, will it? It should only run when the DB is upgraded to 18.

I think you're right. I checked my code and found that is not necessary to run in `19`. Will close this PR.

**Pull request closed without merging**
