### PR TITLE
Implement ToC using PCS getTableOfContents() method

### PR DESCRIPTION
**Pull request by cooltey**
The current way of building ToC has Chinese variant issues (please see "Taiwan" in Traditional Chinese"), and it would be better if we use the PCS `getTableOfContents()` to build the ToC.

https://github.com/wikimedia/mediawiki-services-mobileapps/blob/1001bb39c42ac83ca4095f9921a3e419a3cded02/pagelib/docs/pcs/pcs.md#gettableofcontents

### CODE REVIEW

**Comment by sharvaniharan** [comment]
@cooltey I feel there are a few very nice things in this PR which I have missed on mine. I will incorporate the TOP_SECTION_ID, and updating the section heading without checking for lead. However, I would still like to have the Section Class updated, so we can have them as objects rather than parse the json object. Secondly, after the switch to PageSummary, since the pageProperties will be updated asynchronously, I am not sure that it would be a great idea to setUoToc with it here. So is it ok to close this and I will make those improvements in mine?

**Comment by cooltey** [comment]
@sharvaniharan Sounds good. Just curious that does update the `Section` class affect anything on the editing? I'm seeing some classes are using the `Section` class as well.

**Comment by sharvaniharan** [comment]
@cooltey EditHandler uses the same Section object ... so should be fine.

**Comment by cooltey** [comment]
I see. Closed.

**Pull request closed without merging**
