### PR TITLE
Utilize the displaytitle and fix the variant issues

### PR DESCRIPTION
**Pull request by cooltey**
A counter patch to #448

1. Add a `DISPLAY_TITLE` to `HistoryEntry` related database tables, because we use `PageTitle.getText()` for querying data.
2. Add a `API_TITLE` to `ReadingListPageContract` because when saving a article, the app inserts a `PageTitle.getDisplayText()` to the `TITLE` column.
3. Remove the `convertedText` in `PageTitle`. Use it as the key `title` of the `PageTitle` class.

TODO:
~~1. Update the `DISPLAY_TITLE` after loading the page~~
~~2. Update the logic when saving article offline~~
~~3. Maybe request the `page/summary`, but also can wait until the `mobile-html` patches got merged.~~
~~4. Check `ReadingListDbHelper.instance().findPageInAnyList()` query when switching between variants with same `convertedTitle`.~~

Reading list related ticket: https://phabricator.wikimedia.org/T232384

~~Known issue:
`UpdateHistoryTask` has weird behavior when `upsert` article history if switching the article's variants.~~ 

Tickets:
https://phabricator.wikimedia.org/T227092
https://phabricator.wikimedia.org/T178201

### CODE REVIEW

**Comment by cooltey** [comment]
This PR is ready for review and comments are welcome.

**Comment by cooltey** [comment]
Hi @dbrant and cc @sharvaniharan , I removed the `getConvertedText()` as we discussed, to reduce the complexity.

**Comment by cooltey** [comment]
@dbrant The last commit 100cf9b should fix the Histroy issue you've found.

**Comment by dbrant** [comment]
👍 👍

**Pull request merged**
