### PR TITLE
Add srcset data class for media-list endpoint

### PR DESCRIPTION
**Pull request by cooltey**
The `page/media-list` has the `srcset`, which provides the image URLs and their scales. It will be used in the #546 when downloading images for offline use.

### CODE REVIEW

**Comment by sharvaniharan** [comment]
@cooltey this is also there in my PR for removing PageLead. I have also tied it to the device size, please take a look and lmk which one to keep

**Comment by cooltey** [comment]
> 
> 
> @cooltey this is also there in my PR for removing PageLead. I have also tied it to the device size, please take a look and lmk which one to keep

Is it possible to merge this PR and then you can add the logic you've done in your PR? If so, I will be very appreciated!

 I'd like to continue the work on #546

**Comment by sharvaniharan** [comment]
Sure @cooltey Can we add a provision to get url when scale is specified? and then we can merge

**Comment by cooltey** [comment]
> 
> 
> Sure @cooltey Can we add a provision to get url when scale is specified? and then we can merge

Yes, I write a logic to pick the best scale of the image from a preferred size since there are so many different image sizes.

Please see: 
https://en.wikipedia.org/api/rest_v1/page/media-list/Juice_Wrld 
and 
https://en.wikipedia.org/api/rest_v1/page/media-list/Barack_Obama

**Pull request merged**
