### PR TITLE
Update Balloon library to 1.3.4 to fix content being cutoff on certain devices

### PR DESCRIPTION
**Pull request by cooltey**
@dbrant @sharvaniharan Please help me to test the tooltips to see if the bottom of the content is cut off on your devices.

### CODE REVIEW

**Comment by sharvaniharan** [comment]
Looks good on my Pixel3 @cooltey Will test on more devices with different screen sizes tomorrow!

**Comment by dbrant** [comment]
On my device they look slightly better, but not perfect. One of them has too much padding at the bottom, but the other is slightly clipped at the bottom:

device-2021-03-26-105945

device-2021-03-26-105917

**Comment by sharvaniharan** [comment]
@cooltey Watchlist one is cut-off on Nexus s with a small screen. Other 2 look good:

**Comment by cooltey** [comment]
These are the screenshots from the same config of Nexus S emulators, with API 26 and API 29, and they look good to me.

**Comment by sharvaniharan** [comment]
Yes! I think I did not have the latest version... looks good:
watchlist

**Comment by dbrant** [comment]
@cooltey 👍👍👍 All tooltips look good now.

**Comment by cooltey** [comment]
@dbrant @sharvaniharan Thanks for the testing and now it is ready for merge.

**Pull request merged**
