### PR TITLE
Preview screen for talk messages

### PR DESCRIPTION
**Pull request by sharvaniharan**
**Phab:** https://phabricator.wikimedia.org/T358898

### CODE REVIEW

**Review by cooltey — CHANGES_REQUESTED** [review]
Found several things: 
1. Go to any article and edit a section, the app crashes.
2. Go to a talk thread and click "Reply", when long press on the "Preview" icon, it shows the text from the action bar, and same thing happens to the preview screen as well.
3. Having weird background color when long-press on the hyperlinks in the license text, would it be better to remove it?

**Comment by dbrant** [comment]
> 1. Go to any article and edit a section, the app crashes.

👍 

> 2. Go to a talk thread and click "Reply", when long press on the "Preview" icon, it shows the text from the action bar, and same thing happens to the preview screen as well.

👍 

> 3. Having weird background color when long-press on the hyperlinks in the license text, would it be better to remove it?

This doesn't seem like a problem with this PR, and looking quickly, I'm not sure what's causing that background. Let's investigate separately.

**Comment by sharvaniharan** [comment]
This has passed design review @cooltey @dbrant

**Review by cooltey — APPROVED** [review]
Looks good to me! Will merge this after the new production is released.

**Pull request merged**
