### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by Jvr2022**

### CODE REVIEW

**Comment by cooltey** [comment]
Please provide a description to the PR so reviewers can see the logs of the new update.

**Comment by Jvr2022** [comment]
org.robolectric:robolectric 4.11.1 -> 4.12.1

Fixed a NoClassDefFoundError when invoking ShadowLog APIs outside of a Robolectric environment.
Reduced the amount of spurious log noise that may be generated when attempting to delete temp directories in Windows.
Calling AlwaysOnHotwordDetector constructor reflectively https://github.com/robolectric/robolectric/pull/8549
Bump com.squareup.okhttp3:okhttp-bom from 4.11.0 to 4.12.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8548
Bump androidx.core:core from 1.10.1 to 1.12.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8463
Fix warnings of AndroidSdk.groovy by @utzcoz in https://github.com/robolectric/robolectric/pull/8503
Introducing SensorEventBuilder to replace ShadowSensorManager.createSensorEvent() https://github.com/robolectric/robolectric/pull/8581
Fix LocaleManager.setApplicationLocales(LocaleList) in Android U+ https://github.com/robolectric/robolectric/pull/8583
ShadowDisplayManager: Allowing adding a display with a name. https://github.com/robolectric/robolectric/pull/8591
Bump kotlin from 1.9.10 to 1.9.20 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8594
Bump io.gitlab.arturbosch.detekt:detekt-gradle-plugin from 1.23.1 to 1.23.3 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8595
Bump com.googlecode.libphonenumber:libphonenumber from 8.13.23 to 8.13.24 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8576
Apply Spotless for buildSrc and build script by @utzcoz in https://github.com/robolectric/robolectric/pull/8603
Bump api changes checking compatibility version to 4.11.1 by @utzcoz in https://github.com/robolectric/robolectric/pull/8606
Bump com.android.tools.build:gradle from 8.1.2 to 8.1.3 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8609
Bump com.ibm.icu:icu4j from 73.2 to 74.1 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8611
Update ShadowNativeSQLiteConnection.nativeOpen to not ignore parameters https://github.com/robolectric/robolectric/pull/8612
Set the calling activity in ActivityScenario when run in Robolectric. https://github.com/robolectric/robolectric/pull/8613
Remove duplicated code in ShadowPackageManager.java by @realdadfish in https://github.com/robolectric/robolectric/pull/8614
Improve the fidelity of legacy SQLite error messages by @hoisie in https://github.com/robolectric/robolectric/pull/8615
Do not use isFileEncryptedNativeOrEmulated() on Android 14 and later by @ebiggers in https://github.com/robolectric/robolectric/pull/8616
Ignore nativeruntime-dist-compat from Dependabot by @utzcoz in https://github.com/robolectric/robolectric/pull/8617
Bump com.android.tools.build:gradle from 8.1.3 to 8.1.4 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8618
Bump androidx-fragment from 1.2.0 to 1.6.2 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8593
Bump org.bouncycastle:bcprov-jdk18on from 1.76 to 1.77 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8619
Switch to use gradle/gradle-build-action@v2.9.0 by @utzcoz in https://github.com/robolectric/robolectric/pull/8621
Bump org.jetbrains:annotations from 24.0.1 to 24.1.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8620
Update one GMD config from SDK 33 to 34 by @utzcoz in https://github.com/robolectric/robolectric/pull/8622
Ignore androidx annotation auto-update from Dependabot by @utzcoz in https://github.com/robolectric/robolectric/pull/8624
Bump com.googlecode.libphonenumber:libphonenumber from 8.13.24 to 8.13.25 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8625
Bump androidx.window:window from 1.1.0 to 1.2.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8626
Don't use isUserKeyUnlocked() after Android 14 by @ebiggers in https://github.com/robolectric/robolectric/pull/8635
Remove JDK requirements statement in README.md by @utzcoz in https://github.com/robolectric/robolectric/pull/8636
Enable CodeQL on GitHub Actions by @utzcoz in https://github.com/robolectric/robolectric/pull/8607
Use specific version of gradle/gradle-build-action for codeql.yml by @utzcoz in https://github.com/robolectric/robolectric/pull/8638
Bump kotlin from 1.9.20 to 1.9.21 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8644
Bump gradle/gradle-build-action from 2.9.0 to 2.10.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8647
Bump actions/checkout from 3 to 4 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8646
Add ShadowBuild support for missing supported ABI fields by @jselbo in https://github.com/robolectric/robolectric/pull/8640
Bump com.googlecode.libphonenumber:libphonenumber from 8.13.25 to 8.13.26 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8645
Bump com.diffplug.spotless:spotless-plugin-gradle from 6.22.0 to 6.23.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8642
Bump io.gitlab.arturbosch.detekt:detekt-gradle-plugin from 1.23.3 to 1.23.4 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8643
Bump default minSdk to 19 of AndroidManifest by @utzcoz in https://github.com/robolectric/robolectric/pull/8648
Bump actions/setup-java from 3 to 4 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8664
Bump com.android.tools.build:gradle from 8.1.4 to 8.2.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8667
Remove unused CheckApiChangesPlugin plugin by @utzcoz in https://github.com/robolectric/robolectric/pull/8630
Extract room version to libs.version.toml by @utzcoz in https://github.com/robolectric/robolectric/pull/8674
Bump com.diffplug.spotless:spotless-plugin-gradle from 6.23.0 to 6.23.3 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8665
Bump com.googlecode.libphonenumber:libphonenumber from 8.13.26 to 8.13.27 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8676
Align the behavior of HttpsURLConnection.getDefaultHostnameVerifier in Conscrypt mode. https://github.com/robolectric/robolectric/pull/8677
Add "yMMMd", "yMMMMEEEEd", and "yMMMM" date string formats to support correct date string formats. https://github.com/robolectric/robolectric/pull/8678
Add support for testing InboxStyle notifications. https://github.com/robolectric/robolectric/pull/8681
Create NetworkSpecifierFactory to allow creation of non-public NetworkSpecifier subtypes. https://github.com/robolectric/robolectric/pull/8685
ShadowInputManager.getInputDeviceIds() will now return results that corroborate the return values of .getInputDevices(). https://github.com/robolectric/robolectric/pull/8686
Fix RecordingCanvas.nFinishRecording for Q and R by @hoisie in https://github.com/robolectric/robolectric/pull/8690
Add code comment about the purpose of ShadowNativeBitmapFactory.decodeStream https://github.com/robolectric/robolectric/pull/8692
Ensure ContentResolver.applyBatch(...) return value is valid by @AntonButov in https://github.com/robolectric/robolectric/pull/8669
Bump com.ibm.icu:icu4j from 74.1 to 74.2 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8695
Bump gradle/gradle-build-action from 2.10.0 to 2.11.0 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8698
Make ClassInstrumentorTest more DRY https://github.com/robolectric/robolectric/pull/8699
Ensure that RNG is loaded when SystemFonts.getAvailableFonts is called in Q/R https://github.com/robolectric/robolectric/pull/8703
Bump github/codeql-action from 2 to 3 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8697
Update native method instrumentation to include real native variants https://github.com/robolectric/robolectric/pull/8702
Update ShadowInCallService to not use reflection to set Phone in its constructor. https://github.com/robolectric/robolectric/pull/8705
Bump actions/upload-artifact from 3 to 4 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8696
Revert "Bump actions/upload-artifact from 3 to 4" by @utzcoz in https://github.com/robolectric/robolectric/pull/8707
Add no-op implementation for ShadowNativeFontBuilder.nGetReleaseNativeAssetFunc https://github.com/robolectric/robolectric/pull/8708
Adding service management and updates writing function for ShadowBluetoothGatt and ShadowBluetoothGattServer https://github.com/robolectric/robolectric/pull/8709
Bump gradle/gradle-build-action from 2.11.0 to 2.11.1 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8710
Bump kotlin from 1.9.21 to 1.9.22 by https://github.com/dependabot in https://github.com/robolectric/robolectric/pull/8712
Use File.separator instead of a front slash in system font dir check https://github.com/robolectric/robolectric/pull/8714
Implement ShadowBluetoothA2dp codec switch related APIs https://github.com/robolectric/robolectric/pull/8715
Add additional CTS tests for BitmapFactory.decodeFileDescriptor https://github.com/robolectric/robolectric/pull/8718
Implement ShadowBluetoothA2dp optional codec related APIs https://github.com/robolectric/robolectric/pull/8723
Remove unused Exception from tests of ShadowConnectivityManager by @utzcoz in https://github.com/robolectric/robolectric/pull/8724
Add Roborazzi Integration Tests for Robolectric by @takahirom in https://github.com/robolectric/robolectric/pull/8719
Fix the Test Results Path for graphics tests by @takahirom in https://github.com/robolectric/robolectric/pull/8725
Disable Android T...

dev-drprasad/delete-tag-and-release 0.2.1 -> 1.1

Update package for Node.js v20 by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/47
Use major version instead of exact version by @Apacelus in https://github.com/dev-drprasad/delete-tag-and-release/pull/21
Add Tests and CI by @wardellbagby in https://github.com/dev-drprasad/delete-tag-and-release/pull/17
Migrate to using @actions/core and @actions/github by @wardellbagby in https://github.com/dev-drprasad/delete-tag-and-release/pull/23
Improve the Developer Experience by @wardellbagby in https://github.com/dev-drprasad/delete-tag-and-release/pull/27
Replaced emojis by @Sunny-25 in https://github.com/dev-drprasad/delete-tag-and-release/pull/31
Fix issue where deleting tags failed by @wardellbagby in https://github.com/dev-drprasad/delete-tag-and-release/pull/29
Update action.yml to use Node.js v20 by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/41
Bump word-wrap from 1.2.3 to 1.2.4 by https://github.com/dependabot in https://github.com/dev-drprasad/delete-tag-and-release/pull/36
Bump @babel/traverse from 7.20.5 to 7.24.1 by https://github.com/dependabot in https://github.com/dev-drprasad/delete-tag-and-release/pull/43
Update nodejs 20.x by @JeelsBoobz in https://github.com/dev-drprasad/delete-tag-and-release/pull/40
Update README.md by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/42
Update test.yml to only use Node.js v20 by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/44
Update lint.yml to use Node.js v20 by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/45
Update bundle-check.yml to use Node.js v20 by @thadguidry in https://github.com/dev-drprasad/delete-tag-and-release/pull/46

**Comment by dbrant** [comment]
@Jvr2022  it's perfectly ok to paste a _LINK_ to the release notes, instead of dumping them in a comment.

Also, more seriously, it is very bad practice to @-mention a bunch of usernames, all of whom will receive notifications about this PR, which is a lot of noise. Please don't do that again.

**Comment by Jvr2022** [comment]
I am not doing this again.

**Pull request merged**
