### PR TITLE
Kotlinx Serialization

### PR DESCRIPTION
**Pull request by sharvaniharan**

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
Couldn't [Moshi](https://github.com/square/moshi) be used instead?

**Comment by dbrant** [comment]
> Couldn't [Moshi](https://github.com/square/moshi) be used instead? It was [created](https://medium.com/square-corner-blog/moshi-another-json-processor-624f8741f703) by some developers who worked on Gson, and it also supports Kotlin.

ok, but `kotlinx.serialization` was created by the developers of kotlin.  In what ways is Moshi better?

**Comment by Isira-Seneviratne** [comment]
Moshi works similarly to Gson (albeit with [some differences](https://github.com/square/moshi#borrows-from-gson)), and Moshi also provides the ability to generate JSON adapters at compile time instead of relying on reflection.

**Comment by sharvaniharan** [comment]
#2677

**Pull request closed without merging**
