### PR TITLE
Optimize personalized search results

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T269947

### CODE REVIEW

**Comment by sharvaniharan** [comment]
@cooltey I am getting these results when I follow the steps on the ticket:
film

And Christopher Noal filmography is not in my lists, personalized result icon suggests that it is..

**Comment by cooltey** [comment]
> 
> 
> @cooltey I am getting these results when I follow the steps on the ticket:
> And Christopher Nolan filmography is not in my lists, personalized result icon suggests that it is..

Fixed! Thanks!

**Comment by sharvaniharan** [comment]
Icon look good now... but I might have missed some update we made, but shouldn't it be only one result from history, readinglist and tab each?
one


I am seeing 2 results from history

**Comment by cooltey** [comment]
> 
> 
> Icon look good now... but I might have missed some update we made, but shouldn't it be only one result from history, readinglist and tab each?
> I am seeing 2 results from history

That's weird, I cannot reproduce it. Could you please clear the cache and data and try again?

**Review by sharvaniharan — APPROVED** [review]
I was not able to repro too @cooltey ... Lgtm... Will let @dbrant test on his device once and merge!

**Pull request merged**
