### PR TITLE
Update and modernize existing Widgets.

### PR DESCRIPTION
**Pull request by dbrant**
https://phabricator.wikimedia.org/T354789

### CODE REVIEW

**Comment by sharvaniharan** [comment]
Lgtm, on hold for merge until we get a data measurement plan confirmation.

**Comment by sharvaniharan** [comment]
@dbrant Can we remove the `hold`? 🙌

**Comment by sharvaniharan** [comment]
Getting ready to merge but was curious about one thing:

It works very well for `en`, but for other wikis I feel like the main page parsing or the page title parsing is not working so well.. for eg: Today's `hi` featured [article is glacier national ](https://hi.wikipedia.org/wiki/%E0%A4%97%E0%A5%8D%E0%A4%B2%E0%A5%87%E0%A4%B6%E0%A4%BF%E0%A4%AF%E0%A4%B0_%E0%A4%A8%E0%A5%87%E0%A4%B6%E0%A4%A8%E0%A4%B2_%E0%A4%AA%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%95)park but widget is showing [canada](https://hi.wikipedia.org/wiki/%E0%A4%95%E0%A4%A8%E0%A4%BE%E0%A4%A1%E0%A4%BE)
Guessing this will need to be worked on as part of our actual widget update work and not an issue for this pr?

**Comment by dbrant** [comment]
@sharvaniharan Yep, let's merge and iterate on the finer details as we go.

**Pull request merged**
