### PR TITLE
Update notification list view

### PR DESCRIPTION
**Pull request by cooltey**
https://phabricator.wikimedia.org/T288064

### CODE REVIEW

**Comment by cooltey** [comment]
@dbrant @sharvaniharan The PR is ready for review.

**Review by dbrant — CHANGES_REQUESTED** [review]
@cooltey  I'm continuing to review this, but I noticed a crash:  Open the Notifications activity and very quickly tap the "Mentions" tab (while the content is still being loaded).

**Comment by cooltey** [comment]
> 
> 
> @cooltey I'm continuing to review this, but I noticed a crash: Open the Notifications activity and very quickly tap the "Mentions" tab (while the content is still being loaded).

Yes, I can reproduce it. Fixed.

**Comment by sharvaniharan** [comment]
@cooltey The description text in the designs look like Robin expects some curation of the text like "Mention: ..." or " Message on your talk page:..." etc... it is not the same in the implementation.

**Comment by cooltey** [comment]
> 
> 
> @cooltey The description text in the designs look like Robin expects some curation of the text like "Mention: ..." or " Message on your talk page:..." etc... it is not the same in the implementation. Please Lmk.

Not sure about it, if we add prefix texts to the view, the message will be useless since most of the messages will be truncated. Maybe let's leave it as it is and let Robin decide that?

**Comment by sharvaniharan** [comment]
Lgtm.. @dbrant please merge when you are done.

**Pull request merged**
